FROM python:3.10-slim

WORKDIR /code

COPY ./requirements.txt ./code/requirements.txt

RUN pip install -r ./code/requirements.txt

COPY ./FastApi /code

EXPOSE 8082

CMD ["uvicorn","main:app", "--host","0.0.0.0" ,"--port","8082","--root-path","/opendart-core"]
