apiVersion: v1
kind: Service
metadata:
  name: opendart-test
  namespace: stock
spec:
  selector:
    app: opendart-test
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8082
      nodePort: 30182
      targetPort: 8082
      name: testport
    - protocol: TCP
      port: 22
      nodePort: 30122
      targetPort: 22
      name: sshport
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opendart-test
  namespace: stock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opendart-test
  template:
    metadata:
      labels:
        app: opendart-test
    spec:
      containers:
        - name: opendart-test
          image: muyaho/opendart-test
          stdin: true
          ports:
            - name: testport
              containerPort: 8082
            - name: sshport
              containerPort: 22
          envFrom:
            - configMapRef:
                name: environment-config
